target("bsdiff")
    set_kind("static")
    add_files("*.c")
    add_includedirs(".")

target("bzip2")
    set_kind("static")
    add_files("bzip2/*.c")
    add_includedirs("bzip2")

target("bsdiff_bz2")
    set_kind("binary")
    add_deps("bzip2")
    add_files("bsdiff.c")
    add_includedirs(".")
    add_includedirs("bzip2")
    add_defines("BSDIFF_EXECUTABLE")

target("bspatch_bz2")
    set_kind("binary")
    add_deps("bzip2")
    add_files("bspatch.c")
    add_includedirs(".")
    add_includedirs("bzip2")
    add_defines("BSPATCH_EXECUTABLE")

target("bsdiff_test")
    set_kind("binary")
    add_deps("bsdiff")
    add_files("test/bsdiff_test.c")
    add_includedirs(".")

target("bspatch_test")
    set_kind("binary")
    add_deps("bsdiff")
    add_files("test/bspatch_test.c")
    add_includedirs(".")

target("bspatch_stream_test")
    set_kind("binary")
    add_deps("bsdiff")
    add_files("test/bspatch_stream_test.c")
    add_includedirs(".")